### Get all movies (default pagination, default sort order => winners first)
GET http://localhost:3000/movies
Content-Type: application/json

### Get all movies with pagination (page 2)
GET http://localhost:3000/movies?page=2
Content-Type: application/json

### Get all movies sorted by title
GET http://localhost:3000/movies?sort=title
Content-Type: application/json

### Get all movies with search term
GET http://localhost:3000/movies?search=inception
Content-Type: application/json

### Get all winner movies
GET http://localhost:3000/movies/winners
Content-Type: application/json

### Get movie by ID
GET http://localhost:3000/movies/{{movieId}}
Content-Type: application/json

### Create a new movie
POST http://localhost:3000/movies/new
Content-Type: application/json

{
  "createData": {
    "title": "The Batman",
    "description": "The night begins.",
    "coverImage": "https://example.com/avengers-endgame.jpg",
    "isWinner": false
  }
}

> {% client.global.set("movieId", response.body._id); %}


### Create a new movie with from a details page (with a specified ID)
POST http://localhost:3000/movies/{{movieId}}/new
Content-Type: application/json

{
  "createData": {
    "title": "The Green Mile",
    "description": "A death row corrections officer develops a unique relationship with an inmate who has a miraculous gift.",
    "coverImage": "https://example.com/the-green-mile.jpg",
    "isWinner": false
  }
}

> {% client.global.set("movieId", response.body._id); %}

### Get the list of movie cover images.
GET http://localhost:3000/movies/files/images
Content-Type: application/json

#### Download a movie's cover image by ID
#GET http://localhost:3000/movies/download/{{movieId}}
#Content-Type: application/json

### Delete a movie by ID
DELETE http://localhost:3000/movies/{{movieId}}
Content-Type: application/json

### Update a movie by ID
PATCH http://localhost:3000/movies/{{movieId}}
Content-Type: application/json

{
  "updateData": {
    "title": "Altered",
    "description": "Altered description",
    "coverImage": "https://altered.com/the-green-mile.jpg",
    "isWinner": true
  }
}